version: '3.4'

services:
  appointmentservice.db:
    image: postgres

  appointmentservice.api:
    image: ${DOCKER_REGISTRY-}appointmentserviceapi
    build:
      context: .
      dockerfile: AppointmentService.API/Dockerfile
  
  appointmentservice.proxy:
    image: appointmentservice.proxy
    build:
      dockerfile: appointment-app/Dockerfile
      context: .

volumes:
  postgres_data:
