version: '3.4'

services:
  appointmentservice.db:
    image: postgres
    container_name: appointmentservice.db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=appointments
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  appointmentservice.api:
    image: infernalred/appointmentapi
    build: .
    container_name: appointmentservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TokenKey=${TokenKey}
      - "ConnectionStrings__DefaultConnection=Server=appointmentservice.db;Port=5432;UserId=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=appointments;"
    restart: always
    depends_on:
      - appointmentservice.db
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  
  appointmentservice.proxy:
    image: infernalred/appointmentsproxy
    build: .
    container_name: appointmentservice.proxy
    restart: always
    depends_on:
      - appointmentservice.api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data: