version: '3.4'

services:
  appointmentservice.db:
    container_name: appointmentservice.db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=appointments
    restart: always
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  appointmentservice.api:
    container_name: appointmentservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TokenKey=${TokenKey}
      - "ConnectionStrings__DefaultConnection=Server=appointmentservice.db;Port=5432;UserId=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=appointments;"
    restart: always
    depends_on:
      - appointmentservice.db
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  
  appointmentservice.proxy:
    container_name: appointmentservice.proxy
    restart: always
    depends_on:
      - appointmentservice.api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf